import { Inter, Tenor_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });
const tenorSans = Tenor_Sans({ weight: ["400"], subsets: ["latin"] });

export const metadata = {
  title: "Timbu Shop App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={tenorSans.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
